### ISSUE TITLE
dev: delete types file and import only reth types

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot-rpc#87]
Currently, for speed / simplicity, we replicated types from eth inside types.rs 

Let's delete them all and use only the reth types. Either reth_primitives or reth_primitives::rpc depending on our need.

We still need to discover whether or not reth_rpc::types will disappear as they suggested it was tech debt

**Comment by Eikix** [comment]
@irisdv are you working on this issue?

**Comment by Eikix** [comment]
will not need to "delete" types.rs, but rather, reduce to minimum this file

**Comment by irisdv** [comment]
Yes as part of the #73 I started using only `reth_primitives::rpc` types and replacing the types imported from types.rs otherwise I was facing mismatch errors. 

If we want to replace the types that are in types.rs by native reth types we have two solutions : 
- using `reth_rpc_types` but this result in mismatch errors as some variables in struct expects `reth_primitives` types and not `reth_primitives::rpc` and they don't overlap.

- using types that are in `reth_primitives::rpc` but there are some differences. For example here are the differences for TransactionReceipt : 

**reth_rpc_types**
```
pub struct TransactionReceipt {
    pub transaction_hash: Option<H256>,
    pub transaction_index: Option<U256>,
    pub block_number: Option<U256>,
    pub state_root: Option<H256>,
    pub status_code: Option<U64>,
    pub effective_gas_price: U128,
    pub transaction_type: U256,
}
```

**reth_primitives::rpc::TransactionReceipt**
```
pub struct TransactionReceipt {
    pub transaction_hash: H256,
    pub transaction_index: U64,
    pub block_number: Option<U64>,
    pub root: Option<H256>,
    pub status: Option<U64>,
    pub effective_gas_price: Option<U256>,
    pub transaction_type: Option<U64>,
}
```
Should I proceed with the second solution ?
